import { NextRequest, NextResponse } from 'next/server';

// Telegram webhook handler
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    // Handle /start command
    if (body.message?.text === '/start') {
      const chatId = body.message.chat.id;
      const firstName = body.message.chat.first_name;

      // Send welcome message
      await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text: `👋 Halo ${firstName}! Selamat datang di Equilibria Finance Bot!\n\n📝 Gunakan format berikut untuk mencatat transaksi:\n\n[ tipe ] [ kategori/deskripsi ] [ nominal ]\n\nContoh:\n• pengeluaran makan siang 50000\n• pemasukan gaji bulanan 5000000\n\nKetik /help untuk bantuan.`,
          parse_mode: 'Markdown'
        })
      });

      // Store chat ID for notifications
      localStorage.setItem('equilibria_telegram_chat_id', chatId.toString());

      return NextResponse.json({ ok: true });
    }

    // Handle /help command
    if (body.message?.text === '/help') {
      const chatId = body.message.chat.id;

      await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text: `📚 *Panduan Equilibria Bot*\n\n• Ketik transaksi dengan format:\n  [ tipe ] [ deskripsi ] [ nominal ]\n\n• Contoh:\n  - pengeluaran makan siang 50000\n  - pemasukan freelance 2000000\n\n• Ketik /start untuk melihat perintah\n• Ketik /balance untuk melihat saldo\n\n_Generated by Equilibria_`,
          parse_mode: 'Markdown'
        })
      });

      return NextResponse.json({ ok: true });
    }

    // Handle text messages (parse transactions)
    if (body.message?.text && !body.message.text.startsWith('/')) {
      const chatId = body.message.chat.id;
      const text = body.message.text.toLowerCase();

      // Parse transaction
      let type = 'EXPENSE';
      if (text.includes('pemasukan') || text.includes('income')) {
        type = 'INCOME';
      }

      // Extract amount (last number in message)
      const amountMatch = text.match(/\d+/g);
      if (amountMatch) {
        const amount = parseInt(amountMatch[amountMatch.length - 1]);

        await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            chat_id: chatId,
            text: `✅ Transaksi diterima!\n\n• Tipe: ${type === 'INCOME' ? 'Pemasukan' : 'Pengeluaran'}\n• Nominal: Rp ${amount.toLocaleString('id-ID')}\n\n_Catatan: Data akan diproses oleh sistem_`,
            parse_mode: 'Markdown'
          })
        });

        return NextResponse.json({ ok: true, received: true });
      }

      // No amount found
      await fetch(`https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/sendMessage`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          chat_id: chatId,
          text: `⚠️ Format tidak valid.\n\nGunakan format: [ tipe ] [ deskripsi ] [ nominal ]\n\nContoh: pengeluaran makan siang 50000`
        })
      });

      return NextResponse.json({ ok: true });
    }

    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error('Telegram webhook error:', error);
    return NextResponse.json({ ok: false, error: 'Webhook processing failed' }, { status: 500 });
  }
}

// Health check for webhook
export async function GET() {
  return NextResponse.json({
    status: 'webhook_active',
    bot: process.env.TELEGRAM_BOT_TOKEN ? 'configured' : 'not_configured'
  });
}